apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mydb
        image: stackupiss/northwind-db:v1
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "changeit"
        - name: "MYSQL_DATABASE"
          value: "northwind"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        
