apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  namespace: default
  labels:
    name: fortune
    version: "v1"
spec:
  replicas: 6
  selector:
    matchLabels:
      name: fortune-pod
  template:
    metadata:
      name: fortune-pod
      labels:
        name: fortune-pod
    spec:
      containers:
      - name: fortune-container
        image: stackupiss/fortune:v1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
