---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-configmap
  labels:
    name: weather-configmap
data:
  APP_DEFAULT_CITY: Singapore'

---
apiVersion: v1
kind: Secret
metadata:
  name: weather-secret
data:
  APP_ID: MTZiNjFkMDgxNjAxOWE3M2QzMWY3MzgyNzAxMWFlOGU=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deploy
  namespace: default
  labels:
    name: weather
    version: "v1"
spec:
  replicas: 3
  selector:
    matchLabels:
      name: weather-pod
  template:
    metadata:
      name: weather-pod
      labels:
        name: weather-pod
    spec:
      containers:
      - name: weather-container
        image: stackupiss/weather:v1
        imagePullPolicy: Always
        ports:
        - name: weather-http
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: weather-configmap
        - secretRef:
            name: weather-secret
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    name: weather-service
spec:
  type: LoadBalancer
  selector:
    name: weather-pod
  ports:
  - name: http
    port: 80
    targetPort: weather-http
